[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf
    Parsers_File /fluent-bit/etc/parsers_app.conf

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /tmp/flb_docker.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name         parser
    Match        docker.*
    Key_Name     log
    Parser       app_json
    Reserve_Data Off

[FILTER]
    Name   grep
    Match  docker.*
    Regex  service ^devops-test$

[OUTPUT]
    Name        loki
    Match       docker.*
    Host        loki
    Port        3100
    Labels      job=fluent-bit,app=devops-test
    Line_Format json